thresh: 0.0
tgt_dim: 0
encoder_name: Geoformer
num_epochs: 50
lr_scheduler: plateau
lr_cosine_length: null
lr_warmup_steps: 20000
lr: 0.0001
lr_patience: 15
lr_min: 1.0e-09
lr_factor: 0.8
weight_decay: 0.0
early_stopping_patience: 150
loss_type: MSE
dataset: EDpredict
dataset_arg: energy_U0
dataset_root: /code/retrieve/ed_processed_5w
max_nodes: null
mean: null
std: null
reload: 1
batch_size: 96
inference_batch_size: 128
standardize: false
splits: scaffold
split_mode: scaffold
train_size: 110000
val_size: 10000
test_size: null
num_workers: 6
prior_model: Atomref
max_z: 100
embedding_dim: 256
ffn_embedding_dim: 1024
num_layers: 9
num_heads: 8
cutoff: 5.0
num_rbf: 32
trainable_rbf: false
norm_type: none
dropout: 0.0
attention_dropout: 0.0
activation_dropout: 0.0
activation_function: silu
decoder_type: scalar
aggr: sum
num_classes: 256
pad_token_id: 0
distributed_backend: ddp
ndevices: 1
num_nodes: 1
precision: 32
log_dir: ./logs_geo_x3d_contrastive_x3d_lr5e-5
task: train
seed: 2026
redirect: false
accelerator: gpu
save_interval: 10
point_model: /code/ranking_task/examples/point_model_config/pointmetabase-s-x-3d.yaml
